// Habilidades predefinidas para seleção
export const predefinedSkills = [
  'Análise de dados',
  'Análise financeira',
  'Auditoria',
  'Automação de processos',
  'Atendimento ao cliente',
  'Comunicação escrita',
  'Comunicação verbal',
  'Copywriting',
  'Criação de conteúdo',
  'Design gráfico',
  'Desenho técnico',
  'Digitação',
  'Edição de imagem',
  'Edição de vídeo',
  'Elaboração de relatórios',
  'Escrita criativa',
  'Facilidade com números',
  'Gestão de documentos',
  'Gestão de estoque',
  'Gestão de indicadores',
  'Gestão de mídias sociais',
  'Gestão de projetos',
  'Gestão de tarefas',
  'Liderança de equipe',
  'Mapeamento de processos',
  'Negociação',
  'No-code',
  'Organização de eventos',
  'Planejamento estratégico',
  'Planejamento financeiro',
  'Planejamento logístico',
  'Prospecção de clientes',
  'Redação empresarial',
  'Resolução de problemas',
  'Técnicas de vendas',
  'Treinamento de pessoas',
  'Usabilidade e acessibilidade',
  'UX writing',
  'Visualização de dados',
  'Excel avançado',
  'PowerPoint',
  'Google Planilhas',
  'Google Docs',
  'Figma',
  'Photoshop',
  'Illustrator',
  'Premiere',
  'Power BI',
  'Notion',
  'Trello',
  'Jira',
  'WordPress',
  'ERP',
  'CRM',
  'Salesforce',
  'AutoCAD',
  'SketchUp',
  'Adaptabilidade',
  'Atenção aos detalhes',
  'Autogestão',
  'Autonomia',
  'Colaboração',
  'Comunicação interpessoal',
  'Confiabilidade',
  'Criatividade',
  'Empatia',
  'Ética profissional',
  'Escuta ativa',
  'Gestão de tempo',
  'Inteligência emocional',
  'Iniciativa',
  'Liderança',
  'Negociação interpessoal',
  'Organização',
  'Pensamento analítico',
  'Pensamento crítico',
  'Proatividade',
  'Resiliência',
  'Tomada de decisão',
  'Trabalho em equipe',
  'HTML',
  'CSS',
  'JavaScript',
  'TypeScript',
  'Python',
  'PHP',
  'SQL',
  'React',
  'Node.js',
  'C#',
  'Git',
  'Docker',
  'AWS',
  'Scrum',
  'UI Design',
  'UX Design',
  'Product Design',
  'Machine Learning',
  'Agile',
].sort();

// Opções para o campo de formação acadêmica
export const educationOptions = [
  { value: 'fundamental', label: 'Ensino fundamental' },
  { value: 'medio', label: 'Ensino médio' },
  { value: 'superior_incompleto', label: 'Ensino superior incompleto' },
  { value: 'superior_cursando', label: 'Ensino superior em andamento' },
  { value: 'superior', label: 'Ensino superior completo' },
  { value: 'posgraduacao', label: 'Pós-graduação' },
  { value: 'mestrado', label: 'Mestrado' },
  { value: 'doutorado', label: 'Doutorado' },
];

// Opções para o campo de experiência profissional
export const experienceOptions = [
  { value: 'sem_experiencia', label: 'Sem experiência' },
  { value: 'menos_1', label: 'Menos de 1 ano' },
  { value: '1_2', label: '1-2 anos' },
  { value: '3_5', label: '3-5 anos' },
  { value: '6_10', label: '6-10 anos' },
  { value: 'mais_10', label: 'Mais de 10 anos' },
];

// Opções para o campo de senioridade
export const seniorityOptions = [
  { value: 'estagiario', label: 'Estagiário' },
  { value: 'junior', label: 'Júnior' },
  { value: 'pleno', label: 'Pleno' },
  { value: 'senior', label: 'Sênior' },
  { value: 'especialista', label: 'Especialista' },
  { value: 'lideranca', label: 'Liderança' },
];

// Opções para o campo de disponibilidade
export const availabilityOptions = [
  { value: 'integral', label: 'Tempo integral' },
  { value: 'parcial', label: 'Meio período' },
  { value: 'freelancer', label: 'Freelancer' },
  { value: 'estagio', label: 'Estágio' },
  { value: 'aprendiz', label: 'Jovem aprendiz' },
].sort((a, b) => a.label.localeCompare(b.label));

// Opções para o campo de setor/indústria (empresas)
export const industrySectorOptions = [
  { value: 'agronegocio', label: 'Agronegócio' },
  { value: 'alimentacao', label: 'Alimentação' },
  { value: 'construcao', label: 'Construção civil' },
  { value: 'educacao', label: 'Educação' },
  { value: 'financas', label: 'Finanças' },
  { value: 'industria', label: 'Indústria' },
  { value: 'logistica', label: 'Logística/transporte' },
  { value: 'marketing', label: 'Marketing/publicidade' },
  { value: 'outro', label: 'Outro' },
  { value: 'saude', label: 'Saúde' },
  { value: 'servicos', label: 'Serviços' },
  { value: 'tecnologia', label: 'Tecnologia' },
  { value: 'telecomunicacoes', label: 'Telecomunicações' },
  { value: 'turismo', label: 'Turismo/hotelaria' },
  { value: 'varejo', label: 'Varejo' },
];

// Opções para o campo de porte da empresa
export const companySizeOptions = [
  { value: 'startup', label: 'Startup' },
  { value: 'pequena', label: 'Pequena' },
  { value: 'media', label: 'Média' },
  { value: 'grande', label: 'Grande' },
  { value: 'multinacional', label: 'Multinacional' },
];

// Opções para o campo de modelo de trabalho
export const workModelOptions = [
  { value: 'hibrido', label: 'Híbrido' },
  { value: 'presencial', label: 'Presencial' },
  { value: 'remoto', label: 'Remoto' },
];

// Opções para o campo de jornada de trabalho (empresas)
export const workScheduleOptions = [
  { value: 'comercial', label: 'Comercial' },
  { value: 'flexivel', label: 'Horário flexível' },
  { value: 'reducida', label: '6 horas diárias' },
  { value: 'escala', label: 'Escala/plantão' },
  { value: 'noturno', label: 'Noturno' },
];

// Opções para o campo de benefícios
export const benefitsOptions = [
  { value: 'auxilio_creche', label: 'Auxílio-creche' },
  { value: 'home_office', label: 'Auxílio home office' },
  { value: 'bonus', label: 'Bônus/comissões' },
  { value: 'cursos', label: 'Cursos/capacitação' },
  { value: 'day_off', label: 'Day off de aniversário' },
  { value: 'gympass', label: 'Academia' },
  { value: 'participacao_lucros', label: 'Participação nos lucros' },
  { value: 'plano_odontologico', label: 'Plano odontológico' },
  { value: 'plano_saude', label: 'Plano de saúde' },
  { value: 'seguro_vida', label: 'Seguro de vida' },
  { value: 'vale_alimentacao', label: 'Vale-alimentação' },
  { value: 'vale_refeicao', label: 'Vale-refeição' },
].sort((a, b) => a.label.localeCompare(b.label));

// Opções para o campo de áreas de contratação
export const hiringAreasOptions = [
  { value: 'administrativo', label: 'Administrativo' },
  { value: 'agricultura', label: 'Agricultura' },
  { value: 'atendimento', label: 'Atendimento ao cliente' },
  { value: 'auditoria', label: 'Auditoria' },
  { value: 'biotecnologia', label: 'Biotecnologia' },
  { value: 'comercial', label: 'Comercial' },
  { value: 'compliance', label: 'Compliance' },
  { value: 'contabilidade', label: 'Contabilidade' },
  { value: 'design', label: 'Design' },
  { value: 'desenvolvimento', label: 'Desenvolvimento' },
  { value: 'educacao', label: 'Educação / Treinamento' },
  { value: 'engenharia', label: 'Engenharia' },
  { value: 'financeiro', label: 'Financeiro' },
  { value: 'gestao_de_projetos', label: 'Gestão de projetos' },
  { value: 'juridico', label: 'Jurídico' },
  { value: 'logistica', label: 'Logística' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'pesquisa_desenvolvimento', label: 'Pesquisa e desenvolvimento' },
  { value: 'qualidade', label: 'Qualidade' },
  { value: 'relacoes_publicas', label: 'Relações públicas' },
  { value: 'rh', label: 'Recursos humanos' },
  { value: 'saude', label: 'Saúde' },
  { value: 'sustentabilidade', label: 'Sustentabilidade' },
  { value: 'suporte_tecnico', label: 'Suporte técnico' },
  { value: 'tecnologia', label: 'Tecnologia' },
  { value: 'vendas', label: 'Vendas' },
  { value: 'ux', label: 'UX/UI' },
].sort((a, b) => a.label.localeCompare(b.label));

// Opções para o campo de tecnologias utilizadas pela empresa
export const companyTechnologiesOptions = [
  { value: '3d_printing', label: 'Impressão 3D' },
  { value: 'additive_manufacturing', label: 'Manufatura aditiva' },
  { value: 'agritech', label: 'Tecnologia agrícola' },
  { value: 'ar', label: 'Realidade aumentada' },
  { value: 'autonomous_vehicles', label: 'Veículos autônomos' },
  { value: 'aws', label: 'AWS' },
  { value: 'azure', label: 'Azure' },
  { value: 'big_data', label: 'Big data' },
  { value: 'biometrics', label: 'Biometria' },
  { value: 'biotech', label: 'Biotecnologia' },
  { value: 'blockchain', label: 'Blockchain' },
  { value: 'carbon_capture', label: 'Captura de carbono' },
  { value: 'chatbots', label: 'Chatbots' },
  { value: 'cloud', label: 'Cloud computing' },
  { value: 'computer_vision', label: 'Visão computacional' },
  { value: 'containers', label: 'Containers' },
  { value: 'c_sharp', label: 'C#' },
  { value: 'crispr', label: 'CRISPR' },
  { value: 'cybersec', label: 'Cibersegurança' },
  { value: 'data_fabric', label: 'Data fabric' },
  { value: 'data_governance', label: 'Governança de dados' },
  { value: 'data_lakes', label: 'Lagos de dados' },
  { value: 'data_science', label: 'Ciência de dados' },
  { value: 'devops', label: 'DevOps' },
  { value: 'digital_health', label: 'Saúde digital' },
  { value: 'digital_twins', label: 'Gêmeos digitais' },
  { value: 'docker', label: 'Docker' },
  { value: 'drones', label: 'Drones' },
  { value: 'edge', label: 'Edge computing' },
  { value: 'fintech', label: 'Tecnologia financeira' },
  { value: 'gcp', label: 'Google Cloud' },
  { value: 'genomics', label: 'Genômica' },
  { value: 'green_hydrogen', label: 'Hidrogênio verde' },
  { value: 'hyperautomation', label: 'Hiperautomação' },
  { value: 'ia', label: 'Inteligência artificial' },
  { value: 'insurtech', label: 'Tecnologia em seguros' },
  { value: 'iot', label: 'Internet das coisas' },
  { value: 'java', label: 'Java' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'kubernetes', label: 'Kubernetes' },
  { value: 'legaltech', label: 'Tecnologia jurídica' },
  { value: 'low_code', label: 'Low-code' },
  { value: 'machine_learning', label: 'Machine learning' },
  { value: 'metaverse', label: 'Metaverso' },
  { value: 'microservices', label: 'Microsserviços' },
  { value: 'nanotech', label: 'Nanotecnologia' },
  { value: 'nlp', label: 'Linguagem natural' },
  { value: 'node', label: 'Node.js' },
  { value: 'observability', label: 'Observabilidade' },
  { value: 'php', label: 'PHP' },
  { value: 'proptech', label: 'Tecnologia imobiliária' },
  { value: 'python', label: 'Python' },
  { value: 'quantum', label: 'Computação quântica' },
  { value: 'react', label: 'React' },
  { value: 'robotics', label: 'Robótica avançada' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'serverless', label: 'Arquitetura serverless' },
  { value: 'smart_cities', label: 'Cidades inteligentes' },
  { value: 'smart_home', label: 'Casa inteligente' },
  { value: 'spatial_computing', label: 'Computação espacial' },
  { value: 'sustainable_tech', label: 'Tecnologia sustentável' },
  { value: 'telemedicine', label: 'Telemedicina' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'virtual_reality', label: 'Realidade virtual' },
  { value: 'wearables', label: 'Tecnologia vestível' },
  { value: 'asana', label: 'Asana' },
  { value: 'clickup', label: 'ClickUp' },
  { value: 'figma', label: 'Figma' },
  { value: 'monday', label: 'Monday.com' },
  { value: 'miro', label: 'Miro' },
  { value: 'notion', label: 'Notion' },
  { value: 'slack', label: 'Slack' },
  { value: 'teams', label: 'Microsoft Teams' },
  { value: 'zoom', label: 'Zoom' },
  { value: 'google_docs', label: 'Google Docs' },
  { value: 'google_sheets', label: 'Google Sheets' },
  { value: 'google_slides', label: 'Google Slides' },
  { value: 'google_workspace', label: 'Google Workspace' },
  { value: 'office365', label: 'Office 365' },
  { value: 'excel', label: 'Excel' },
  { value: 'powerpoint', label: 'PowerPoint' },
  { value: 'word', label: 'Word' },
  { value: 'power_bi', label: 'Power BI' },
  { value: 'tableau', label: 'Tableau' },
  { value: 'looker', label: 'Looker' },
  { value: 'datastudio', label: 'Data Studio' },
  { value: 'photoshop', label: 'Photoshop' },
  { value: 'illustrator', label: 'Illustrator' },
  { value: 'lightroom', label: 'Lightroom' },
  { value: 'canva', label: 'Canva' },
  { value: 'jira', label: 'Jira' },
  { value: 'confluence', label: 'Confluence' },
  { value: 'zendesk', label: 'Zendesk' },
  { value: 'intercom', label: 'Intercom' },
  { value: 'hubspot', label: 'HubSpot' },
  { value: 'salesforce', label: 'Salesforce' },
  { value: 'pipedrive', label: 'Pipedrive' },
  { value: 'erp', label: 'ERP' },
  { value: 'sap', label: 'SAP' },
  { value: 'totvs', label: 'TOTVS' },
  { value: 'crm', label: 'CRM' },
  { value: 'magento', label: 'Magento' },
  { value: 'shopify', label: 'Shopify' },
  { value: 'wordpress', label: 'WordPress' },
  { value: 'elementor', label: 'Elementor' },
  { value: 'woocommerce', label: 'WooCommerce' },
  { value: 'prestashop', label: 'PrestaShop' },
  { value: 'mailchimp', label: 'Mailchimp' },
  { value: 'rdstation', label: 'RD Station' },
  { value: 'semrush', label: 'SEMrush' },
  { value: 'hotjar', label: 'Hotjar' },
  { value: 'typeform', label: 'Typeform' },
  { value: 'survey_monkey', label: 'SurveyMonkey' },
  { value: 'firebase', label: 'Firebase' },
].sort((a, b) => a.label.localeCompare(b.label));

// Lista de níveis superiores de educação (para verificações condicionais)
export const higherEducationLevels = [
  'superior_incompleto',
  'superior_cursando',
  'superior',
  'posgraduacao',
  'mestrado',
  'doutorado',
];

// Opções de idiomas para seleção de idiomas no perfil (ordenado)
export const languageOptions = [
  'Português',
  'Inglês',
  'Espanhol',
  'Francês',
  'Alemão',
  'Italiano',
  'Mandarim',
  'Japonês',
  'Russo',
  'Árabe',
  'Hindi',
  'Coreano',
].sort((a, b) => a.localeCompare(b, 'pt-BR'));

// Níveis de proficiência para seleção de idiomas (não ordenado)
export const proficiencyLevels = [
  { value: 'basic', label: 'Básico' },
  { value: 'intermediate', label: 'Intermediário' },
  { value: 'advanced', label: 'Avançado' },
  { value: 'fluent', label: 'Fluente' },
  { value: 'native', label: 'Nativo' },
];
